config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  
  root 'staticpages#index'
  
  get '/pages' => 'pages#index'
  get '/next-event-is-still-planned' => 'staticpages#next_event_is_still_planned'
  get '/ninjas-works' => 'staticpages#ninjas_works'
  
  get '/auth/:provider/callback' => 'admin/users#callback'
  
  namespace :admin do
    resources :posts # => /admin/posts etc...
    get 'sessions/index'
    get 'sessions/new'
    get 'sessions/login'
  end
  
  scope module: :public do
    resources :posts, only: [:show,:index] # => /posts etc...
  end
  
  resources :pages, only: [:show], :path => '/'
  

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
  end
  def next_event_is_still_planned
  end
  def ninjas_works
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/index.html.haml
%body
  - provide(:desc, 'CoderDojo 岡山 岡南 の公式サイトです。 CoderDojo とは、小中高生を対象とした無料プログラミング道場です。参加者（ニンジャ）の作りたいものを先生（メンター）がニンジャ目線で一緒に考え、アドバイスをし、 そしてモノづくりの楽しさを共有します！')
  .mdl-layout.mdl-js-layout
    %header.mdl-layout__header.mdl-layout__header--scroll.layout-transparent
      .mdl-layout__header-row
        / Title
        %span.mdl-layout-title
          %img{:alt => "CoderDojo Konan Okayama", :src => "#{asset_path "coderdojo-konan-header-logo.png"}"}/
        / Add spacer, to align navigation to the right
        .mdl-layout-spacer
        / Navigation
        %nav.mdl-navigation
          %a.mdl-navigation__link{:href => "#{@first_link[:url]}"}= @first_link[:text]
          %a.mdl-navigation__link{:href => "#{@second_link[:url]}"}= @second_link[:text]
          %a.mdl-navigation__link{:href => "#{@third_link[:url]}"}= @third_link[:text]
          %a.mdl-navigation__link{:href => "#{@fourth_link[:url]}"}= @fourth_link[:text]
      .header-section
        .header-section-text
          %h2 子供のためのプログラミング道場
          %h1 CoderDojo Konan Okayama
          %br/
          %p
            CoderDojo 岡山 岡南 は、小中高生を対象とした
            %strong> 無料プログラミング道場
            です。
            %br/
            参加者（ニンジャ）の作りたいものを先生（メンター）がニンジャ目線で一緒に考え、
            %br/
            アドバイスをし、 そしてモノづくりの楽しさを共有します！
        .header-section-button
          - unless next_event_url.nil?
            = link_to "次回の開催Check!", next_event_url, class: 'btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-js-ripple-effect'
    .mdl-layout__drawer
      %span.mdl-layout-title CoderDojo Konan Okayama Official Site
      %nav.mdl-navigation
        %a.mdl-navigation__link{:href => "#{@first_link[:url]}"}= @first_link[:text]
        %a.mdl-navigation__link{:href => "#{@second_link[:url]}"}= @second_link[:text]
        %a.mdl-navigation__link{:href => "#{@third_link[:url]}"}= @third_link[:text]
        %a.mdl-navigation__link{:href => "#{@fourth_link[:url]}"}= @fourth_link[:text]
    %main.mdl-layout__content
      %article
        %section#about-section
          .about-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text CoderDojo って？
            .mdl-card__supporting-text
              / Twitter
              .button.twitter.twitter-share-button-style
                %a.twitter-share-button{"data-lang" => "en", "data-text" => "CoderDojo Konan Okayama Official Site", "data-url" => "#{request.original_url}", :href => "https://twitter.com/share"} Tweet
              / Facebook
              .button.facebook.fb-share-button-style
                .fb-share-button{"data-href" => "#{request.original_url}", "data-layout" => "button_count", "data-mobile-iframe" => "true", "data-size" => "small"}
                  %a.fb-xfbml-parse-ignore{:href => "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}&src=sdkpreparse", :target => "_blank"} Share
              %p
                CoderDojo は7〜17歳の子どもを対象にした無料で参加できるプログラミング道場(サークル)です。
                %br/
                2011年にアイルランドで始まり、世界では70カ国・1,200の道場、日本では全国に84以上の道場があります。(2017/5/27現在)
              %p
                各地のCoderDojoは、それぞれの有志がボランティアで運営していて、
                %br/
                CoderDojoでは、Ninja同士（参加している子供をNinjaといいます。）で教えあったり、
                %br/
                わからないことがあれば、現役プログラマーを中心としたメンターさんに質問したりできます。
              %p CoderDojo で学べる内容は道場ごとに異なります。例えば、次の内容を学べる道場があります。
              %ul
                %li Scratch, Hour of Code
                %li HTML, CSS, JavaScript
                %li PHP, Python, Ruby, Unity
                %li Arduino, Raspberry Pi など
              %p 道場ごとに内容も規模も違いますが、Ninjaの自主性を重視している姿勢は一緒です。
        %section#language-section
          .language-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text CoderDojo 岡山 岡南での主な言語・ツール
            .mdl-card__supporting-text
              .mdl-grid
                .mdl-cell.mdl-cell--3-col.mdl-cell--8-col-tablet.language-section-card-cell
                  %img{:alt => "Scratch Cat", :src => "#{asset_path "scratch-cat.png"}"}/
                  %p
                    %a{:href => "https://scratch.mit.edu/"} Scratch
                .mdl-cell.mdl-cell--3-col.mdl-cell--8-col-tablet.language-section-card-cell
                  %img{:alt => "Java Logo", :src => "#{asset_path "java-original.png"}"}/
                  %p
                    %a{:href => "https://www.java.com/ja/"} Java
                .mdl-cell.mdl-cell--3-col.mdl-cell--8-col-tablet.language-section-card-cell
                  %img{:alt => "Web系言語", :src => "#{asset_path "web-lang.png"}"}/
                  %p
                    %a HTML・CSS・JavaScript
                .mdl-cell.mdl-cell--3-col.mdl-cell--8-col-tablet.language-section-card-cell
                  %img{:alt => "Ruby (on Rails)", :src => "#{asset_path "ruby-original.png"}"}/
                  %p
                    %a{:href => "https://www.ruby-lang.org/ja/"} Ruby (on Rails)
        %section#summary-section
          .summary-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text CoderDojo 岡山 岡南 の 開催概要
            .mdl-card__supporting-text
              %p
                %strong> 毎月 第三日曜日
                に開催しています。
              %p
                %strong> 事前申し込み制
                です。申し込みページよりお申し込みください。
              %p PCは無料でレンタル可能ですが、事前申込で、定員があります。
              %p 開始時刻の10分前には会場に到着しておいてください。
              %p 水筒などをお持ちの方は、開催前に指定場所においてください。
              %p
                %strong また、水分補給などは、指定場所ですること！（精密機械を扱っているため。）（配線に注意！）
        %section#partner-section
          .partner-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text パートナー
            .mdl-card__supporting-text
              %h3 CoderDojo 岡山 岡南 は、これらのパートナー様のご支援によって成り立っております！
              %ul.partner-list
                %li.partner-list-item
                  %img#sakura-internet-logo{:src => "#{asset_path "sakura-internet.png"}"}/
                  .mdl-tooltip{"data-mdl-for" => "sakura-internet-logo"} 「さくらのクラウド」の無償提供
                  %p SAKURA INTERNET INC. 様
                %li.partner-list-item
                  %img#esa-io-logo{:src => "#{asset_path "esa.png"}"}/
                  .mdl-tooltip{"data-mdl-for" => "esa-io-logo"} ドキュメント共有サービスの提供
                  %p ESA.IO 様
                %li.partner-list-item
                  %img#rimgate-logo{:src => "#{asset_path "non-logo.png"}"}/
                  .mdl-tooltip{"data-mdl-for" => "rimgate-logo"} サーバー・ドメイン代などの支援
                  %p リムゲイト株式会社 様
        %section#contact-section
          .contact-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text お問い合わせ
            .mdl-card__supporting-text
              #wufoo-mv590ug0y8dwt7
                Fill out my
                = succeed "." do
                  %a{:href => "https://coderdojokonancontact.wufoo.com/forms/mv590ug0y8dwt7"} online form
              #wuf-adv{:style => "font-family:inherit;font-size: small;color:#a7a7a7;text-align:center;display:block;"}
                There are tons of
                %a{:href => "http://www.wufoo.com/features/"} Wufoo features
                to help make your forms awesome.
              %br/
              :javascript
                var mv590ug0y8dwt7;(function(d, t) {
                                  var s = d.createElement(t), options = {
                                  'userName':'coderdojokonancontact',
                                  'formHash':'mv590ug0y8dwt7',
                                  'autoResize':true,
                                  'height':'560',
                                  'async':true,
                                  'host':'wufoo.com',
                                  'header':'show',
                                  'ssl':true};
                                  s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
                                  s.onload = s.onreadystatechange = function() {
                                  var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
                                  try { mv590ug0y8dwt7 = new WufooForm();mv590ug0y8dwt7.initialize(options);mv590ug0y8dwt7.display(); } catch (e) {}};
                                  var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
                                  })(document, 'script');
              .sns-contact-block
                .fb-page{"data-adapt-container-width" => "true", "data-hide-cover" => "false", "data-href" => "https://www.facebook.com/Coderdojo.Konan/", "data-show-facepile" => "true", "data-small-header" => "false", "data-tabs" => "timeline"}
                  %blockquote.fb-xfbml-parse-ignore{:cite => "https://www.facebook.com/Coderdojo.Konan/"}
                    %a{:href => "https://www.facebook.com/Coderdojo.Konan/"} CoderDojo 岡山 岡南
                .twitter-timeline-box
                  %a.twitter-follow-button{"data-show-count" => "false", :href => "https://twitter.com/CoderDojo_Konan"} Follow @CoderDojo_Konan
                  %a.twitter-timeline{"data-height" => "500", "data-theme" => "light", "data-width" => "340", :href => "https://twitter.com/coderdojo_konan?ref_src=twsrc%5Etfw"} Tweets by coderdojo_konan
      %footer.mdl-mini-footer
        .mdl-mini-footer__left-section
          .mdl-logo
            CoderDojo Konan Okayama Official Site
          %ul.mdl-mini-footer__link-list
            %li Copyright © 2018 CoderDojo Konan Okayama
        .mdl-mini-footer__right-section
          %button.mdl-mini-footer__social-btn
            %a{:href => "https://twitter.com/coderdojo_konan", :target => "_blank", :title => "Twitter"}
              %i.fa.fa-twitter
          %button.mdl-mini-footer__social-btn
            %a{:href => "http://facebook.com/Coderdojo.Konan/", :target => "_blank", :title => "Facebook"}
              %i.fa.fa-facebook
          %button.mdl-mini-footer__social-btn
            %a{:href => "https://www.instagram.com/coderdojo_konan/", :target => "_blank", :title => "Instagram"}
              %i.fa.fa-instagram
          %button.mdl-mini-footer__social-btn
            %a{:href => "https://github.com/CoderDojo-Konan-Okayama", :target => "_blank", :title => "Github"}
              %i.fa.fa-github

app/views/staticpages/next_event_is_still_planned.html.haml
%body
  - provide(:title, '次回の開催はまだ計画中です...')
  - provide(:desc, '次回の開催はまだ計画中です...')
  .mdl-layout.mdl-js-layout.pages-layout
    %header.mdl-layout__header.mdl-layout__header--scroll.pages-layout__header
      .mdl-layout__header-row
        / Title
        %span.mdl-layout-title
          %a{:href => root_path}
            %img{:alt => "CoderDojo Konan Okayama", :src => "#{asset_path 'coderdojo-konan-header-logo.png'}"}/
        / Add spacer, to align navigation to the right
        .mdl-layout-spacer
        / Navigation
        %nav.mdl-navigation
          %a.mdl-navigation__link{:href => "#{@first_link[:url]}"}= @first_link[:text]
          %a.mdl-navigation__link{:href => "#{@second_link[:url]}"}= @second_link[:text]
          %a.mdl-navigation__link{:href => "#{@third_link[:url]}"}= @third_link[:text]
          %a.mdl-navigation__link{:href => "#{@fourth_link[:url]}"}= @fourth_link[:text]
    .mdl-layout__drawer
      %span.mdl-layout-title CoderDojo Konan Okayama Official Site
      %nav.mdl-navigation
        %a.mdl-navigation__link{:href => "#{@first_link[:url]}"}= @first_link[:text]
        %a.mdl-navigation__link{:href => "#{@second_link[:url]}"}= @second_link[:text]
        %a.mdl-navigation__link{:href => "#{@third_link[:url]}"}= @third_link[:text]
        %a.mdl-navigation__link{:href => "#{@fourth_link[:url]}"}= @fourth_link[:text]
    %main.mdl-layout__content
      %article
        %section#pages-section
          .pages-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text 次回の開催はまだ計画中です...
            #pages_contents.mdl-card__supporting-text
              .entry-content
                %h1{:style => "text-align: center;"}
                  %span{:style => "color: #ff6600;"} 次回の開催はまだ計画中です… 😉
                %h2{:style => "text-align: center;"}
                  %span{:style => "text-decoration: underline;"} 日時、場所などが決定したら、各種SNSや、ブログなどでお知らせします！
                %h3{:style => "text-align: center;"}
                  %a{:href => "http://konan-coderdojo.connpass.com/"} イベント申込サービス（Connpass）グループページ
                %h4{:style => "text-align: center;"} このグループに参加すると、イベントが公開される度にメールでお知らせされます！！
                %h3{:style => "text-align: center;"} 決定するまで、もうしばらくお待ちください！
                %p{:style => "text-align: center;"}= link_to 'トップページに戻る', root_path
            %footer.mdl-mini-footer
              .mdl-mini-footer__left-section
                .mdl-logo
                  CoderDojo Konan Okayama Official Site
                %ul.mdl-mini-footer__link-list
                  %li Copyright © 2018 CoderDojo Konan Okayama
              .mdl-mini-footer__right-section
                %button.mdl-mini-footer__social-btn
                  %a{:href => "https://twitter.com/coderdojo_konan", :target => "_blank", :title => "Twitter"}
                    %i.fa.fa-twitter
                %button.mdl-mini-footer__social-btn
                  %a{:href => "http://facebook.com/Coderdojo.Konan/", :target => "_blank", :title => "Facebook"}
                    %i.fa.fa-facebook
                %button.mdl-mini-footer__social-btn
                  %a{:href => "https://www.instagram.com/coderdojo_konan/", :target => "_blank", :title => "Instagram"}
                    %i.fa.fa-instagram
                %button.mdl-mini-footer__social-btn
                  %a{:href => "https://github.com/CoderDojo-Konan-Okayama", :target => "_blank", :title => "Github"}
                    %i.fa.fa-github

app/views/staticpages/ninjas_works.html.haml
%body
  - provide(:title, '参加したNinjaの作品')
  - provide(:desc, '参加したNinjaの作品です。<p>とてもユニークな発想で、とても面白いです。制作者のコメントと共にご覧ください。')
  .mdl-layout.mdl-js-layout.pages-layout
    %header.mdl-layout__header.mdl-layout__header--scroll.pages-layout__header
      .mdl-layout__header-row
        / Title
        %span.mdl-layout-title
          %a{:href => root_path}
            %img{:alt => "CoderDojo Konan Okayama", :src => "#{asset_path "coderdojo-konan-header-logo.png"}"}/
        / Add spacer, to align navigation to the right
        .mdl-layout-spacer
        / Navigation
        %nav.mdl-navigation
          %a.mdl-navigation__link{:href => "#{@first_link[:url]}"}= @first_link[:text]
          %a.mdl-navigation__link{:href => "#{@second_link[:url]}"}= @second_link[:text]
          %a.mdl-navigation__link{:href => "#{@third_link[:url]}"}= @third_link[:text]
          %a.mdl-navigation__link{:href => "#{@fourth_link[:url]}"}= @fourth_link[:text]
    .mdl-layout__drawer
      %span.mdl-layout-title CoderDojo Konan Okayama Official Site
      %nav.mdl-navigation
        %a.mdl-navigation__link{:href => "#{@first_link[:url]}"}= @first_link[:text]
        %a.mdl-navigation__link{:href => "#{@second_link[:url]}"}= @second_link[:text]
        %a.mdl-navigation__link{:href => "#{@third_link[:url]}"}= @third_link[:text]
        %a.mdl-navigation__link{:href => "#{@fourth_link[:url]}"}= @fourth_link[:text]
    %main.mdl-layout__content
      %article
        %section.pages-section
          .pages-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text 参加したNinjaの作品
            .pages-contents.mdl-card__supporting-text
              .twitter-share-button-style
                %a.twitter-share-button{"data-hashtags" => "CoderDojo岡南", "data-related" => "CoderDojo_Konan,CoderDojoJapan", "data-show-count" => "false", "data-text" => "作品紹介 - CoderDojo 岡山 岡南 公式HP", "data-url" => "#{request.url}", "data-via" => "CoderDojo_Konan", :href => "https://twitter.com/share?ref_src=twsrc%5Etfw"} Tweet
                %script{:async => "", :charset => "utf-8", :src => "https://platform.twitter.com/widgets.js"}
              .fb-share-button.fb-share-button-style{"data-href" => "#{request.url}", "data-layout" => "button_count", "data-mobile-iframe" => "true", "data-size" => "small"}
                %a.fb-xfbml-parse-ignore{:href => "https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fcoderdojo-konan.jp%2F&src=sdkpreparse", :target => "_blank"} シェア
              %p 参加したNinjaの作品です。
              %p とてもユニークな発想で、とても面白いです。
              %p 制作者のメッセージと一緒にご覧ください。
              %p
                %strong なお、作品を実際に動かすには、 Adobe Flash が必要となります！
              %p 対応した端末でご覧ください！
        %section.pages-section
          .pages-section-card.mdl-card.mdl-shadow--2dp
            .mdl-card__title
              %h1.mdl-card__title-text アンダイン的な何か
            .pages-contents.mdl-card__supporting-text
              .pages-col
                .ninjas-works-video
                  %iframe#ytplayer{:allowfullscreen => "", :frameborder => "0", :height => "300", :src => "https://www.youtube.com/embed/_QdREfAxlAY?loop=1", :type => "text/html", :width => "400"}
              .pages-col
                .ninjas-works-impressions
                  .ninjas-works-container
                    .pages-col.ninjas-icon
                      %img{:src => "#{asset_path "ninjas-icon/ucchi.jpg"}"}/
                      %br/
                      %p
                        うっちー
                        %br/
                    .pages-col
                      %h4 作ったNinjaのメッセージ
                      %p
                        赤いハートを上下左右キーで動かして、猫が飛ばしてくる矢印をよけるゲームです。
                        %br/
                        赤、青矢印はまっすぐ飛びますが、白い矢印はハートに向かって追尾してきて、
                        %br/
                        さらにあたってしまうと少しの間ハートが止まります。
                        %br/
                        しかし、白矢印は赤や青よりダメージが低いです。
                        %br/
                        矢印の色別に速度や動きを変えたりと工夫しました。
                        %br/
                      = link_to "遊ぶ / コードを見てみる", 'https://scratch.mit.edu/projects/210911830/',                                                               |
                        class: 'btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-js-ripple-effect', target: "_new" |
      %footer.mdl-mini-footer
        .mdl-mini-footer__left-section
          .mdl-logo
            CoderDojo Konan Okayama Official Site
          %ul.mdl-mini-footer__link-list
            %li Copyright © 2018 CoderDojo Konan Okayama
        .mdl-mini-footer__right-section
          %button.mdl-mini-footer__social-btn
            %a{:href => "https://twitter.com/coderdojo_konan", :target => "_blank", :title => "Twitter"}
              %i.fa.fa-twitter
          %button.mdl-mini-footer__social-btn
            %a{:href => "http://facebook.com/Coderdojo.Konan/", :target => "_blank", :title => "Facebook"}
              %i.fa.fa-facebook
          %button.mdl-mini-footer__social-btn
            %a{:href => "https://www.instagram.com/coderdojo_konan/", :target => "_blank", :title => "Instagram"}
              %i.fa.fa-instagram
          %button.mdl-mini-footer__social-btn
            %a{:href => "https://github.com/CoderDojo-Konan-Okayama", :target => "_blank", :title => "Github"}
              %i.fa.fa-github