config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  
  root 'staticpages#index'
  
  get '/pages' => 'pages#index'
  get '/next-event-is-still-planned' => 'staticpages#next_event_is_still_planned'
  get '/ninjas-works' => 'staticpages#ninjas_works'
  
  get '/auth/:provider/callback' => 'admin/users#callback'
  
  namespace :admin do
    resources :posts # => /admin/posts etc...
    get 'sessions/index'
    get 'sessions/new'
    get 'sessions/login'
  end
  
  scope module: :public do
    resources :posts, only: [:show,:index] # => /posts etc...
  end
  
  resources :pages, only: [:show], :path => '/'
  

end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged
  
  scope :published, -> { where("published_at IS NOT NULL").where("published_at <= ?", Time.now) }
  scope :draft, -> { where("published_at IS NULL OR published_at > ?", Time.now) }
  
  def should_generate_new_friendly_id?
    slug_changed? || super
  end
  
  def published?
    Post.all.published.exists? self.id
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::Base
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /admin/posts
  # GET /admin/posts.json
  def index
    @posts = Post.all
  end

  # GET /admin/posts/new
  def new
    @post = Post.new
  end
  
  # GET /posts/1
  # GET /posts/1.json
  def show
    @body = Kramdown::Document.new(@post.body).to_html
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :title, :published_at, :author_id, :slug)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :title, :published_at, :author_id, :slug)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.haml
= simple_form_for [:admin, @post] do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  
  = f.input :title
  = f.input :slug
  = f.input :published_at, as: :date_time_picker
  = f.input :body
  = f.input :author_id
  = f.button :submit

app/views/admin/posts/edit.html.haml
.box.box-default
  .box-header.with-border
    %h3.box-title 編集
    .box-tools.pull-right
      %a{:href => @post}
        %button.btn.btn-box-tool.btn.btn-box-tool{:type => "button", :data-widget => "collapse"}
          Show
      %a{:href => admin_posts_path}
        %button.btn.btn-box-tool.btn.btn-box-tool{:type => "button", :data-widget => "collapse"}
          Back
  .box-body
    = render 'form'

app/views/admin/posts/index.html.haml
- provide :title, '記事一覧'

.box.box-default
  .box-header.with-border
    %h3.box-title 記事一覧
    .box-tools.pull-right
      %a{:href => new_admin_post_path}
        %button.btn.btn-box-tool.btn.btn-box-tool{:type => "button", :data-widget => "collapse"}
          %i.fa.fa-plus
          新規作成
  .box-body
    %table#posts-list.table.table-striped.table-bordered
      %thead
        %tr
          %th Title
          %th Published at
          %th Author
          %th Published?
          %th
          %th
          %th
          
      %tbody
        - @posts.each do |post|
          %tr
            %td= post.title
            %td= post.published_at
            %td= post.author_id
            %td
              - if post.published?
                Published
              - else
                Not Published
            %td= link_to 'Preview', [:admin, post], :target=>["_new"]
            %td= link_to 'Edit', edit_admin_post_path(post)
            %td= link_to 'Destroy', [:admin, post], method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/posts/new.html.haml
.box.box-default
  .box-header.with-border
    %h3.box-title 新規作成
    .box-tools.pull-right
      %a{:href => admin_posts_path}
        %button.btn.btn-box-tool.btn.btn-box-tool{:type => "button", :data-widget => "collapse"}
          Back
  .box-body
    = render 'form'